### ISSUE TITLE
Bug: not saving for the full duration if stored value is an object

### ISSUE THREAD

**Issue by RaZeSloth** [CesiumLabs/quickmongo#44]
In the latest version of Quickmongo, there is a bug with the timed deletion of a document. When saving an object/array it will not save for the full duration specified. For string and number option the feature works as intended.

Works as intended.
```js
await db.set('test', 'test\'s value', 2 * 60);
```

Does not work, deletes as soon as mongoDB can
```js
await db.set('test', {}, 2 * 60);
```

**Comment by DevAndromeda** [comment]
https://github.com/CesiumLabs/quickmongo/releases/tag/v5.1.2
