### ISSUE TITLE
Bug: Not able to pull an object.

### ISSUE THREAD

**Issue by RaZeSloth** [CesiumLabs/quickmongo#45]
Pulling an object using `db.pull()` does not remove it from the array when the value is an object. This has been in Quickmongo for a very long time. It does work with strings and numbers.

Does not work.
```js
// Document data => { ID: "key", data: [{ key: "value" }] }
await db.pull("key", { key: "value" });
// Returns =>  [{ key: "value" }] 
```
Does work.
```js
// Document data => { ID: "key", data: ["value"] }
await db.pull("key", "value");
// Returns => []
```

**Comment by DevAndromeda** [comment]
@zyrouge bump
