### ISSUE TITLE
Bug? Or Error? 

### ISSUE THREAD

**Issue by ThisMe124** [CesiumLabs/quickmongo#47]
Why Error Like This? 
![IMG_20220210_125305](https://user-images.githubusercontent.com/88891071/153339742-5935a83b-89c4-4946-82a2-102aaed89d44.jpg)
 
On Nodejs v12

**Comment by ThisMe124** [comment]
And More Error!! 
![IMG_20220210_141146](https://user-images.githubusercontent.com/88891071/153348580-ac05d7c5-eee1-4eab-b090-a5d28ab0d078.jpg)

**Comment by zyrouge** [comment]
@DevAndromeda Something wrong with obfuscation?

**Comment by DevAndromeda** [comment]
The package is minified due to which the error message appears that way

**Comment by ThisMe124** [comment]
what does that mean?

**Comment by rhygg** [comment]
> And More Error!! ![IMG_20220210_141146](https://user-images.githubusercontent.com/88891071/153348580-ac05d7c5-eee1-4eab-b090-a5d28ab0d078.jpg)

Okay, a quick guide on the errors displayed. 
This one isn't a **quickmongo** error.

> Why Error Like This? ![IMG_20220210_125305](https://user-images.githubusercontent.com/88891071/153339742-5935a83b-89c4-4946-82a2-102aaed89d44.jpg)
> 
> On Nodejs v12

As for this, the package is **minified** i.e., the size of the package has been minimized or lessened, therefore the errors are displayed in such a way.

**Comment by ThisMe124** [comment]
Okay
