### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by anondev-sudo** [CesiumLabs/quickmongo#48]
Hello, I have updated to the latest version and the DB is not started.

I get error `Error: DATABASE_NOT_READY` when I want to set something.

```
const { Database } = require('quickmongo');
const db = new Database(process.env.db);
```
The mongoDB uri is correct, didn't change it

**Comment by DevAndromeda** [comment]
hello, could you check the [new example](https://github.com/CesiumLabs/quickmongo#example)? You need to add `db.connect();` in order to connect to mongo.

**Comment by anondev-sudo** [comment]
Ok, btw how to set custom collection name? I want to make more database with different collections to separate data

**Comment by DevAndromeda** [comment]
Same as quick.db

```js
const coll = new db.table("MyCollection");
```
