### ISSUE TITLE
Cannot read properties of undefined (reading 'model')

### ISSUE THREAD

**Issue by TheWutyAbad** [CesiumLabs/quickmongo#49]
hi i have a problem..
how i can define a model or schema? 

setting a collection not import anything in DB

**Comment by zyrouge** [comment]
If you are asking about different collections, you can use `.table('tablename')` method. If you are asking about model or schema, they aren't supported anymore.

**Comment by TheWutyAbad** [comment]
Well, I set the collection, but nothing enters the database. I made two different tables and entered the data without the schema...

**Comment by TheWutyAbad** [comment]
I said that even without the schema, nothing can be entered into the database I also tested the table, it gives an error I'm sorry, I found out more about version 4
